// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopApp.Data;

namespace ShopApp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211227141948_adding-relationships")]
    partial class addingrelationships
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShopApp.Models.ItemsList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<int?>("ShopsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShopsId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpiryDate = new DateTime(2021, 12, 27, 14, 19, 47, 975, DateTimeKind.Utc).AddTicks(7435),
                            Name = "Obuoliai",
                            ShopId = 2
                        },
                        new
                        {
                            Id = 2,
                            ExpiryDate = new DateTime(2021, 12, 27, 14, 19, 47, 975, DateTimeKind.Utc).AddTicks(7660),
                            Name = "Sviestas",
                            ShopId = 1
                        },
                        new
                        {
                            Id = 3,
                            ExpiryDate = new DateTime(2021, 12, 27, 14, 19, 47, 975, DateTimeKind.Utc).AddTicks(7663),
                            Name = "Miltai",
                            ShopId = 1
                        },
                        new
                        {
                            Id = 4,
                            ExpiryDate = new DateTime(2021, 12, 27, 14, 19, 47, 975, DateTimeKind.Utc).AddTicks(7665),
                            Name = "Kiausiniai",
                            ShopId = 1
                        },
                        new
                        {
                            Id = 5,
                            ExpiryDate = new DateTime(2021, 12, 27, 14, 19, 47, 975, DateTimeKind.Utc).AddTicks(7667),
                            Name = "Cinamonas",
                            ShopId = 2
                        });
                });

            modelBuilder.Entity("ShopApp.Models.ShopsList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Maxima"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Lidl"
                        });
                });

            modelBuilder.Entity("ShopApp.Models.ItemsList", b =>
                {
                    b.HasOne("ShopApp.Models.ShopsList", "Shops")
                        .WithMany("Items")
                        .HasForeignKey("ShopsId");

                    b.Navigation("Shops");
                });

            modelBuilder.Entity("ShopApp.Models.ShopsList", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
